[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/race"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200
